### ISSUE TITLE
TAX/VAT client number in Invoice

### ISSUE THREAD

**Issue by rogmoreno** [firegento/firegento-pdf#115]
It´s possible add the client VAT/TAX number net to the name in the invoice?

**Comment by ottonet** [comment]
Actually I just implemented this myself. @Schrank's March 3rd 2014 comment is using the [deprecated](http://www.magentocommerce.com/boards/m/viewthread/282317/) customer taxvat field, and that's why it didn't show for @rogmoreno and me.  

As of CE 1.7 and up you should add the following code: 

    {{depend vat_id}}<br/>VAT ID: {{var vat_id}}{{/depend}} 

to System -> Configuration -> Customers -> Customer Configuration -> Address Templates -> PDF (and optionally to HTML and Text fields as well)

**Comment by Schrank** [comment]
Thanks for explaining!
