### ISSUE TITLE
Logo in wrong size

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-pdf#233]
Maybe we have a bug, when you have no "Logo Ratio" defined, that the logo is only 1% big.

TODO:
- check
- fix if needed: add a standard config value of 100(%)

**Comment by sprankhub** [comment]
Well... The default logo ratio in the config IS 100... See https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/etc/config.xml#L165 But you are right, one can remove the value completely, so that it is empty. Then, 1% was used. I fixed this in https://github.com/firegento/firegento-pdf/commit/40ab480062c4b8394c9725d1ea14fd4ac547dd42.

**Comment by Schrank** [comment]
Thanks :)
