### ISSUE TITLE
Blank screen in backend

### ISSUE THREAD

**Issue by ese-ese** [firegento/firegento-pdf#248]
Hey, I have an Issue using the Firegento-PDF module. 
When I click on "PDF Ausdrucke" in the configuration-panel I get a blank, white screen.
I already deleted the caches and logged out and in again. But I can't get it work...

Magento Version is 1.8.1. (with the latest Security Patch)
The URL (of the white screen): domain.com/index.php/admin/system_config/edit/section/sales_pdf/key/5d3e8ac222affba2b30b8f9342351f23/

**Comment by sprankhub** [comment]
Please make sure that you use the latest release. Clear the cache, logout and login again from the admin panel and check if the problem persists.

**Comment by ese-ese** [comment]
I installed via Magento Connect, That's supposed to be the latest release, right?
I've cleared the caches, I logged in and out, still a white screen

**Comment by sprankhub** [comment]
Magento Connect is always a bad choice. But yeah, this should be the latest release. Maybe something failed during the installation, so that files are missing.

I personally do not have any other idea without having a look at the installation. I cannot reproduce this issue. You could of course hire @Schrank or me to have a look at the issue.

**Comment by ese-ese** [comment]
Allright, thanks for the advice. I'll try the installation with the master.zip.
