### ISSUE TITLE
Linebreak Zeilenumbruch an der Position, wo eigentl. die Artikelnr. aufgeführt ist

### ISSUE THREAD

**Issue by lazolive** [firegento/firegento-pdf#252]
Hello,
in our Magento Shop (Magento DE Vers. 1.9.0.1 v1), we sell products with unique licenses.
I`ve added an Attribute with multi-line text separate with comma.
In the invoices, I want to print this license/s.

With querying in the file: `Default.php` (you'll find under: `app/code/community/FireGento/Pdf/Model/Items`) I get the following results: `12345, 23456, 34567, 45678, 67890, 78901, 89012, 90123`.
With the PHP function `exlpode(",", $query_licenses["value"])`, I select only one of them, like `$licenses["0"]`.

If there is only one order of this article then there is no problem, because it needs only one line.
But if there is more then one order of the same article for example five pieces, than a for-loop happens five times.
The problem is,that I want this numbers to appear under one another.
I first tried to put in a `<br />` after `$lines[0][] = array( 'text' => $license . '<br />',` but it didn't work. It only appeared as a text.

Could you please help me to solve this problem.

Thank you!

![license_invoice_linebreak_qty](https://cloud.githubusercontent.com/assets/13330167/8670910/18a1c31e-2a21-11e5-8648-9a21a7f8e316.jpg)

Kind regards,
lazo-live

**Comment by sprankhub** [comment]
1. Please write issues in English, so that more people can understand them.
2. Please add some screenshots, so that your issue becomes clearer.

**Comment by lazolive** [comment]
can nobody help me??

**Comment by sprankhub** [comment]
We do not get any notification if you edit your post, sorry. Will have a look at it later. But please mind that this is a open source project we all develop in our free time. It is free of charge. So please be patient.

**Comment by sprankhub** [comment]
Thanks, the explanation is much better and clearer now.

1. You should never use mysql PHP functions like `mysql_query` in Magento. You should use the Magento abstractions for that. And IF you do, you should use prepared statements. Otherwise, you introduce many security problems.
2. You should not directly edit `app/code/community/FireGento/Pdf/Model/Items/Default.php`, but [write your own engine](https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine). Otherwise, all your changes are lost with the next update of the extension.
3. You can have a look how this is done with the options. You can do it in exactly the same way. The `text` property of the `$lines` array accepts arrays. It will print each entry of the array in a separate line. As a test, I added the following code at [this position](https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Items/Default.php#L86):

        $lines[][] = array(
            'text' => array('first line', 'second line'),
            'feed' => $pdf->margin['left'] + 135
        );

    This results in the following output:
![image](https://cloud.githubusercontent.com/assets/930199/8727069/edde54bc-2bdd-11e5-90ef-6c9ac02fd903.png)
