### ISSUE TITLE
qty on invoice can not be first

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-pdf#339]
I'm trying to change the column order for invoice to be qty first, but it doesn'T work.

**Before save:**
![bildschirmfoto 2017-01-08 um 14 54 04](https://cloud.githubusercontent.com/assets/379680/21750398/7fc2c69a-d5b2-11e6-97a6-7bb7d297c356.png)

**after save:**
![bildschirmfoto 2017-01-08 um 14 54 13](https://cloud.githubusercontent.com/assets/379680/21750399/8143d2ca-d5b2-11e6-8f59-00c0aded2dd9.png)

**Comment by sprankhub** [comment]
This is due to a strange behaviour of [scriptaculous' Sortable](https://madrobby.github.io/scriptaculous/sortable/). There are certain criteria for IDs of the draggable items:

1. Each item must have a unique id.
2. The item id must contain an underscore (_)
3. The item id cannot begin with an underscore or a hyphen

The IDs must match the regular expression `/^[^_\-](?:[A-Za-z0-9\-\_]*)[_](.*)$/`. See http://krues8dr.com/blog/2009/02/10/scriptaculous-sortable-create-onupdate-event-not-firing/.

I now changed the ID prefix from `pdf-column` to `pdf_column` and it seems to work fine.
