### ISSUE TITLE
FontSize

### ISSUE THREAD

**Issue by cbellow** [firegento/firegento-pdf#345]
The PDFs produce headers, subtotals and taxes with different fontsizes. It would be nice to have an option on the magento configuration to specify fontsizes so one can specify same size or different size for the printouts.

**Comment by sprankhub** [comment]
The font sizes of the subtotals/taxes should match. Not sure what you mean with the "headers". You could provide a screenshot, so that I can see what you mean. Making each font-size configurable is not really possible with the current configuration / setup. You can always [write your own engine](https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine) if you want to customise anything.

**Comment by Schrank** [comment]
I think making everything configurable is overwhelming and we need a lot of images to explain to the user, which setting is what. I prefer to focus on a new version which creates pdfs out of html and css
