### ISSUE TITLE
Tax Rate Is Not Shown

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-pdf#73]
The tax rate for the tax for shipping and handling is not shown. This is not compliant to German law and has to be changed. The tax rate should be shown in brackets directly after "Steuer für Versand & Bearbeitung" as it is with the "MwSt. (19.0000%)".

![image](https://f.cloud.github.com/assets/930199/961217/ad8ee39c-04cd-11e3-8241-887b400d7d77.png)

**Comment by winkelsdorf** [comment]
Any update on this issue? Or alternative setting? iirc setting the shipping tax to full product tax allows including the shipping tax in the tax sum (giving just a total tax), still correct?

**Comment by Schrank** [comment]
Yes, I checked it and I don't see any easy way to get the percentage. So we have three ways:

1. we save the percentage while submiting the order so we know it
2. we calculate it just in time and round it somehow (bad idea)
3. We recreate the mechanism to get the shipping tax and calculate it

**Comment by sprankhub** [comment]
Thanks for your effort @Schrank! My opinions on your ideas:

1. This would make the extension more complex and would leave "garbage" in the database when the extension is uninstalled (since we would need a new order attribute which could not be deleted automatically). Hence, I do not really prefer this solution.
2. It feels kind of hacky, but should be a quite reliable way, no? If we have (1) the tax amount for shipping and handling and (2) the total amount of the shipping and handling, it should easily be possible to calculate the correct rate. (1) and (2) are shown on the PDF (see screenshot above), so we have this information. We just need to make sure that we reliably know whether (2) is including or excluding tax.
3. If I understand correctly, this would mean that we calculate the shipping tax with the current configuration. But it may have been changed in the meantime, so that the PDF is not correct for old orders. Hence, I would vote against it.

**Comment by avogt** [comment]
I wasted some time on this at the hackathon in Leipzig. This is quite crappy. The Totals are really messed up. The main reason for this issue here is, that the shipping tax percentage is calculated on rounded prices from the db wich leads to the possible solutions meantioned above.
I build up a solution on getting the real numbers with a precision of 4 and were able to get a good tax percentage like 7.0000 or 19.0000 (e.g for germany).
By now I'm trying to get the invoice a new feature to sum up taxes by there tax percentage for german law purposes but it is not that easy as the types for same item values differ (e.g string "2.3800" vs float 1.9782 vs. formatted string "2.56 €") so it isn't easy to sum that up. The getter on models and helpers are partial hardcoded to Mage_X Classes which leads to an never ending rewrite cascade by now. If I make it to finish my feature it will automatically fix this issue.

**Comment by Schrank** [comment]
Fixed long time ago with an ugly hack.
